// <auto-generated />
namespace Attendance_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class intialModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intialModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202004060001572_intialModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
